test:
  script: 
    - sudo dpkg --add-architecture i386 
    - sudo apt-get update 
    - sudo apt-get install libx11-6:i386 libgl1-mesa-glx:i386 libfontconfig1:i386 libssl1.0.0:i386 
    - sudo apt-get install gcc-multilib
    - ./scripts/test.sh
